package com.spring.model2;

// Generated Apr 26, 2015 4:54:59 AM by Hibernate Tools 4.3.1

/**
 * Data generated by hbm2java
 */
public class Data implements java.io.Serializable {

	private Integer dataId;
	private Users users;
	private String FName;
	private String LName;
	private String idNo;
	private String address;
	private String phone;
	private String mobile;
	private String mail;
	private String fax;
	private String otherMail;

	public Data() {
	}

	public Data(Users users, String FName, String LName, String idNo, String address, String phone, String mobile,
			String mail, String fax, String otherMail) {
		this.users = users;
		this.FName = FName;
		this.LName = LName;
		this.idNo = idNo;
		this.address = address;
		this.phone = phone;
		this.mobile = mobile;
		this.mail = mail;
		this.fax = fax;
		this.otherMail = otherMail;
	}

	public Integer getDataId() {
		return this.dataId;
	}

	public void setDataId(Integer dataId) {
		this.dataId = dataId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	public String getLName() {
		return this.LName;
	}

	public void setLName(String LName) {
		this.LName = LName;
	}

	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getOtherMail() {
		return this.otherMail;
	}

	public void setOtherMail(String otherMail) {
		this.otherMail = otherMail;
	}

}
