package com.spring.model2;

// Generated Apr 26, 2015 4:54:59 AM by Hibernate Tools 4.3.1

/**
 * Logo generated by hbm2java
 */
public class Logo implements java.io.Serializable {

	private LogoId id;

	public Logo() {
	}

	public Logo(LogoId id) {
		this.id = id;
	}

	public LogoId getId() {
		return this.id;
	}

	public void setId(LogoId id) {
		this.id = id;
	}

}
