package com.spring.model2;

// Generated Apr 26, 2015 4:54:59 AM by Hibernate Tools 4.3.1

import java.util.Arrays;

/**
 * LogoId generated by hbm2java
 */
public class LogoId implements java.io.Serializable {

	private String name;
	private String engName;
	private byte[] logo;

	public LogoId() {
	}

	public LogoId(String name, String engName, byte[] logo) {
		this.name = name;
		this.engName = engName;
		this.logo = logo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEngName() {
		return this.engName;
	}

	public void setEngName(String engName) {
		this.engName = engName;
	}

	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogoId))
			return false;
		LogoId castOther = (LogoId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this
				.getName().equals(castOther.getName())))
				&& ((this.getEngName() == castOther.getEngName()) || (this.getEngName() != null
						&& castOther.getEngName() != null && this.getEngName().equals(castOther.getEngName())))
				&& ((this.getLogo() == castOther.getLogo()) || (this.getLogo() != null && castOther.getLogo() != null && Arrays
						.equals(this.getLogo(), castOther.getLogo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getEngName() == null ? 0 : this.getEngName().hashCode());
		int logoHashcode = 0;
		byte[] logoProperty = this.getLogo();
		if (logoProperty != null) {
			logoHashcode = 1;
			for (int i = 0; i < logoProperty.length; i++) {
				logoHashcode = 37 * logoHashcode + logoProperty[i];
			}
		}

		result = 37 * result + logoHashcode;

		return result;
	}

}
