package com.spring.model2;

// Generated Apr 26, 2015 4:54:59 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PedigreeType generated by hbm2java
 */
public class PedigreeType implements java.io.Serializable {

	private Integer typeId;
	private String gene;
	private String type;
	private Integer price;
	private Set pedigrees = new HashSet(0);

	public PedigreeType() {
	}

	public PedigreeType(String gene) {
		this.gene = gene;
	}

	public PedigreeType(String gene, String type, Integer price, Set pedigrees) {
		this.gene = gene;
		this.type = type;
		this.price = price;
		this.pedigrees = pedigrees;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Set getPedigrees() {
		return this.pedigrees;
	}

	public void setPedigrees(Set pedigrees) {
		this.pedigrees = pedigrees;
	}

}
