package com.spring.model2;

// Generated Apr 26, 2015 4:54:59 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Pedigree generated by hbm2java
 */
public class Pedigree implements java.io.Serializable {

	private Integer pedigreeId;
	private Color color;
	private Pedigree pedigreeByPedigreeSireId;
	private Pedigree pedigreeByPedigreeDamId;
	private PedigreeType pedigreeType;
	private Users users;
	private String CName;
	private String sex;
	private String calved;
	private String bbfaNo;
	private String bbfaF;
	private String privateNo;
	private String band;
	private String breeder;
	private String owner;
	private String dateDelivery;
	private String breed;
	private String farmName;
	private String ownerName;
	private String pay;
	private Set pedigreesForPedigreeSireId = new HashSet(0);
	private Set pedigreesForPedigreeDamId = new HashSet(0);

	public Pedigree() {
	}

	public Pedigree(Color color, Pedigree pedigreeByPedigreeSireId, Pedigree pedigreeByPedigreeDamId,
			PedigreeType pedigreeType, Users users, String CName, String sex, String calved, String bbfaNo,
			String bbfaF, String privateNo, String band, String breeder, String owner, String dateDelivery,
			String breed, String farmName, String ownerName, String pay, Set pedigreesForPedigreeSireId,
			Set pedigreesForPedigreeDamId) {
		this.color = color;
		this.pedigreeByPedigreeSireId = pedigreeByPedigreeSireId;
		this.pedigreeByPedigreeDamId = pedigreeByPedigreeDamId;
		this.pedigreeType = pedigreeType;
		this.users = users;
		this.CName = CName;
		this.sex = sex;
		this.calved = calved;
		this.bbfaNo = bbfaNo;
		this.bbfaF = bbfaF;
		this.privateNo = privateNo;
		this.band = band;
		this.breeder = breeder;
		this.owner = owner;
		this.dateDelivery = dateDelivery;
		this.breed = breed;
		this.farmName = farmName;
		this.ownerName = ownerName;
		this.pay = pay;
		this.pedigreesForPedigreeSireId = pedigreesForPedigreeSireId;
		this.pedigreesForPedigreeDamId = pedigreesForPedigreeDamId;
	}

	public Integer getPedigreeId() {
		return this.pedigreeId;
	}

	public void setPedigreeId(Integer pedigreeId) {
		this.pedigreeId = pedigreeId;
	}

	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	public Pedigree getPedigreeByPedigreeSireId() {
		return this.pedigreeByPedigreeSireId;
	}

	public void setPedigreeByPedigreeSireId(Pedigree pedigreeByPedigreeSireId) {
		this.pedigreeByPedigreeSireId = pedigreeByPedigreeSireId;
	}

	public Pedigree getPedigreeByPedigreeDamId() {
		return this.pedigreeByPedigreeDamId;
	}

	public void setPedigreeByPedigreeDamId(Pedigree pedigreeByPedigreeDamId) {
		this.pedigreeByPedigreeDamId = pedigreeByPedigreeDamId;
	}

	public PedigreeType getPedigreeType() {
		return this.pedigreeType;
	}

	public void setPedigreeType(PedigreeType pedigreeType) {
		this.pedigreeType = pedigreeType;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getCalved() {
		return this.calved;
	}

	public void setCalved(String calved) {
		this.calved = calved;
	}

	public String getBbfaNo() {
		return this.bbfaNo;
	}

	public void setBbfaNo(String bbfaNo) {
		this.bbfaNo = bbfaNo;
	}

	public String getBbfaF() {
		return this.bbfaF;
	}

	public void setBbfaF(String bbfaF) {
		this.bbfaF = bbfaF;
	}

	public String getPrivateNo() {
		return this.privateNo;
	}

	public void setPrivateNo(String privateNo) {
		this.privateNo = privateNo;
	}

	public String getBand() {
		return this.band;
	}

	public void setBand(String band) {
		this.band = band;
	}

	public String getBreeder() {
		return this.breeder;
	}

	public void setBreeder(String breeder) {
		this.breeder = breeder;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getDateDelivery() {
		return this.dateDelivery;
	}

	public void setDateDelivery(String dateDelivery) {
		this.dateDelivery = dateDelivery;
	}

	public String getBreed() {
		return this.breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	public String getFarmName() {
		return this.farmName;
	}

	public void setFarmName(String farmName) {
		this.farmName = farmName;
	}

	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public String getPay() {
		return this.pay;
	}

	public void setPay(String pay) {
		this.pay = pay;
	}

	public Set getPedigreesForPedigreeSireId() {
		return this.pedigreesForPedigreeSireId;
	}

	public void setPedigreesForPedigreeSireId(Set pedigreesForPedigreeSireId) {
		this.pedigreesForPedigreeSireId = pedigreesForPedigreeSireId;
	}

	public Set getPedigreesForPedigreeDamId() {
		return this.pedigreesForPedigreeDamId;
	}

	public void setPedigreesForPedigreeDamId(Set pedigreesForPedigreeDamId) {
		this.pedigreesForPedigreeDamId = pedigreesForPedigreeDamId;
	}

}
