package com.spring.model2;

// Generated Apr 26, 2015 4:54:59 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege implements java.io.Serializable {

	private int privilegeId;
	private String status;
	private Set userses = new HashSet(0);

	public Privilege() {
	}

	public Privilege(int privilegeId) {
		this.privilegeId = privilegeId;
	}

	public Privilege(int privilegeId, String status, Set userses) {
		this.privilegeId = privilegeId;
		this.status = status;
		this.userses = userses;
	}

	public int getPrivilegeId() {
		return this.privilegeId;
	}

	public void setPrivilegeId(int privilegeId) {
		this.privilegeId = privilegeId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
