package com.spring.model2;

// Generated Apr 26, 2015 4:54:59 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Report generated by hbm2java
 */
public class Report implements java.io.Serializable {

	private Integer reportId;
	private Bank bank;
	private Date date;
	private Integer pedigreeId;
	private int dataId;

	public Report() {
	}

	public Report(Bank bank, int dataId) {
		this.bank = bank;
		this.dataId = dataId;
	}

	public Report(Bank bank, Date date, Integer pedigreeId, int dataId) {
		this.bank = bank;
		this.date = date;
		this.pedigreeId = pedigreeId;
		this.dataId = dataId;
	}

	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	public Bank getBank() {
		return this.bank;
	}

	public void setBank(Bank bank) {
		this.bank = bank;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getPedigreeId() {
		return this.pedigreeId;
	}

	public void setPedigreeId(Integer pedigreeId) {
		this.pedigreeId = pedigreeId;
	}

	public int getDataId() {
		return this.dataId;
	}

	public void setDataId(int dataId) {
		this.dataId = dataId;
	}

}
