package com.spring.model2;

// Generated Apr 26, 2015 4:54:59 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userId;
	private Privilege privilege;
	private String username;
	private String password;
	private Set pedigrees = new HashSet(0);
	private Set datas = new HashSet(0);

	public Users() {
	}

	public Users(Privilege privilege, String username, String password, Set pedigrees, Set datas) {
		this.privilege = privilege;
		this.username = username;
		this.password = password;
		this.pedigrees = pedigrees;
		this.datas = datas;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getPedigrees() {
		return this.pedigrees;
	}

	public void setPedigrees(Set pedigrees) {
		this.pedigrees = pedigrees;
	}

	public Set getDatas() {
		return this.datas;
	}

	public void setDatas(Set datas) {
		this.datas = datas;
	}

}
