package com.spring.model;

// Generated Mar 27, 2015 9:39:21 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.spring.model.Report;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name="bank")
public class Bank implements java.io.Serializable {

	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	
	@Column(name="name")
	private String name;
	
	@Column(name="def_name")
	private String defName;
	
@OneToMany(fetch=FetchType.LAZY,mappedBy="bank")
@Fetch(FetchMode.SUBSELECT)
	private List<Report> report;
	/*private Set reports = new HashSet(0);*/

	public Bank() {
	}

	public Bank(int id) {
		this.id = id;
	}

public Bank( String name, String defName) {
		this.name = name;
		this.defName = defName;
		
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDefName() {
		return this.defName;
	}

	public void setDefName(String defName) {
		this.defName = defName;
	}

	public List<Report> getReport() {
		return report;
	}

	public void setReport(List<Report> report) {
		this.report = report;
	}

}
