package com.spring.model;

// Generated Mar 29, 2015 5:24:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name="color")
public class Color implements java.io.Serializable {

	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	
	@Column(name="cname")
	private String name;
	
	@Transient
	private List<Pedigree> pedigree;
/*	private Set pedigrees = new HashSet(0);*/

	public Color() {
	}

	public Color(int id) {
		this.id = id;
	}

	public Color(int id, String name/*, Set pedigrees*/) {
		this.id = id;
		this.name = name;
	/*	this.pedigrees = pedigrees;*/
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Pedigree> getPedigree() {
		return pedigree;
	}

	public void setPedigree(List<Pedigree> pedigree) {
		this.pedigree = pedigree;
	}

}
