package com.spring.model;

// Generated Mar 29, 2015 5:24:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;



/**
 * Data generated by hbm2java
 */
@Entity
@Table(name="data")
public class Data implements java.io.Serializable {

	@Id
	@Column(name="data_id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	
	@OneToOne(cascade = {CascadeType.ALL})
	@JoinColumn(name = "user_id")
	private Users users;
	
	@Column(name="f_name")
	private String FName;
	
	@Column(name="l_name")
	private String LName;
	
	@Column(name="id_no")
	private String idNo;
	
	@Column(name="address")
	private String address;
	
	@Column(name="phone")
	private String phone;
	
	@Column(name="mobile")
	private String mobile;
	
	@Column(name="mail")
	private String mail;
	
	@Column(name="fax")
	private String fax;
	
	@Column(name="other_mail")
	private String otherMail;
	
	
	@OneToMany(fetch=FetchType.LAZY,mappedBy="dataId")
	@Fetch(FetchMode.SUBSELECT)
		private List<Report> report;
	

	public Data() {
	}

	public Data(int id) {
		this.id = id;
	}

/*	public Data(int id, Users users, String FName, String LName, String idNo, String address, String phone,
			String mobile, String mail, String fax, String otherMail, Set userses) {
		this.id = id;
		this.users = users;
		this.FName = FName;
		this.LName = LName;
		this.idNo = idNo;
		this.address = address;
		this.phone = phone;
		this.mobile = mobile;
		this.mail = mail;
		this.fax = fax;
		this.otherMail = otherMail;
		this.userses = userses;
	}*/

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	public String getLName() {
		return this.LName;
	}

	public void setLName(String LName) {
		this.LName = LName;
	}

	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getOtherMail() {
		return this.otherMail;
	}

	public void setOtherMail(String otherMail) {
		this.otherMail = otherMail;
	}
	
	public List<Report> getReport() {
		return report;
	}

	public void setReport(List<Report> report) {
		this.report = report;
	}


}
