package com.spring.model;

// Generated Mar 31, 2015 3:57:24 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Pedigree generated by hbm2java
 */
@Entity
@Table(name = "pedigree")
public class Pedigree implements java.io.Serializable {

	@Id
	@Column(name = "pedigree_id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;
	
	@ManyToOne
	@JoinColumn(name = "color_id")
	private Color color;
	
	
/*	private Pedigree pedigreeByPedigreeSireId;
	private Pedigree pedigreeByPedigreeDamId;*/
	
	@ManyToOne
	@JoinColumn(name = "pedigree_type_type_id1")
	private PedigreeType pedigreeType;
	
	
	
	@ManyToOne
	@JoinColumn(name = "users_user_id")
	private Users usersByUsersUserId;
	
	@Column(name = "c_name")
	private String CName;
	
	@Column(name = "sex")
	private String sex;
	
	@Column(name = "calved")
	private String calved;
	
	@Column(name = "bbfa_no")
	private String bbfaNo;
	
	@Column(name = "bbfa_f")
	private String bbfaF;
	
	@Column(name = "private_no")
	private String privateNo;
	
	@Column(name = "band")
	private String band;
	
	@Column(name = "breeder")
	private String breeder;
	
	@Column(name = "owner")
	private String owner;
	
	@Column(name = "date_delivery")
	private String dateDelivery;
	
	@Column(name = "breed")
	private String breed;
	
	@Column(name = "farm_name")
	private String farmName;
	
	@Column(name = "owner_name")
	private String ownerName;
	
	@Column(name = "pay")
	private String pay;
	
	//พ่อตัวไหน
	@ManyToOne
	@JoinColumn(name="pedigree_sire_id")
	private Pedigree pedigreesireid;
	
	//แม่ตัวไหนตัวไหน
	@ManyToOne
	@JoinColumn(name="pedigree_dam_id")
	private Pedigree pedigreedamid;
	
	public Pedigree getPedigreesireid() {
		return pedigreesireid;
	}

	public void setPedigreesireid(Pedigree pedigreesireid) {
		this.pedigreesireid = pedigreesireid;
	}

	public Pedigree getPedigreedamid() {
		return pedigreedamid;
	}

	public void setPedigreedamid(Pedigree pedigreedamid) {
		this.pedigreedamid = pedigreedamid;
	}

	public List<Pedigree> getPedigreesireides() {
		return pedigreesireides;
	}

	public void setPedigreesireides(List<Pedigree> pedigreesireides) {
		this.pedigreesireides = pedigreesireides;
	}

	public List<Pedigree> getPedigreedamides() {
		return pedigreedamides;
	}

	public void setPedigreedamides(List<Pedigree> pedigreedamides) {
		this.pedigreedamides = pedigreedamides;
	}

	//ลูกตัวผู้
	@OneToMany(mappedBy="pedigreesireid")
	private List<Pedigree> pedigreesireides;
	
	//ลูกตัวเมีย
		@OneToMany(mappedBy="pedigreedamid")
		private List<Pedigree> pedigreedamides;
	
/*	private Set pedigreesForPedigreeSireId = new HashSet(0);
	private Set pedigreesForPedigreeDamId = new HashSet(0);*/
		
		@OneToMany(fetch=FetchType.LAZY,mappedBy="pedigreeId")
		@Fetch(FetchMode.SUBSELECT)
			private List<Report> report;

	public Pedigree() {
	}

	public Pedigree(int id, Color color, PedigreeType pedigreeType, Users usersByUsersDataDataId,
			Users usersByUsersUserId) {
		this.id = id;
		this.color = color;
		this.pedigreeType = pedigreeType;
		this.usersByUsersUserId = usersByUsersUserId;
	}

	public Pedigree(int id, Color color, Pedigree pedigreeByPedigreeSireId, Pedigree pedigreeByPedigreeDamId,
			PedigreeType pedigreeType, Users usersByUsersDataDataId, Users usersByUsersUserId, String CName,
			String sex, String calved, String bbfaNo, String bbfaF, String privateNo, String band, String breeder,
			String owner, String dateDelivery, String breed, String farmName, String ownerName, String pay/*,
			Set pedigreesForPedigreeSireId, Set pedigreesForPedigreeDamId*/) {
		this.id = id;
		this.color = color;
/*		this.pedigreeByPedigreeSireId = pedigreeByPedigreeSireId;
		this.pedigreeByPedigreeDamId = pedigreeByPedigreeDamId;*/
		this.pedigreeType = pedigreeType;
		this.usersByUsersUserId = usersByUsersUserId;
		this.CName = CName;
		this.sex = sex;
		this.calved = calved;
		this.bbfaNo = bbfaNo;
		this.bbfaF = bbfaF;
		this.privateNo = privateNo;
		this.band = band;
		this.breeder = breeder;
		this.owner = owner;
		this.dateDelivery = dateDelivery;
		this.breed = breed;
		this.farmName = farmName;
		this.ownerName = ownerName;
		this.pay = pay;
		/*this.pedigreesForPedigreeSireId = pedigreesForPedigreeSireId;
		this.pedigreesForPedigreeDamId = pedigreesForPedigreeDamId;*/
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Color getColor() {
		return color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	/*public Pedigree getPedigreeByPedigreeSireId() {
		return this.pedigreeByPedigreeSireId;
	}

	public void setPedigreeByPedigreeSireId(Pedigree pedigreeByPedigreeSireId) {
		this.pedigreeByPedigreeSireId = pedigreeByPedigreeSireId;
	}

	public Pedigree getPedigreeByPedigreeDamId() {
		return this.pedigreeByPedigreeDamId;
	}

	public void setPedigreeByPedigreeDamId(Pedigree pedigreeByPedigreeDamId) {
		this.pedigreeByPedigreeDamId = pedigreeByPedigreeDamId;
	}*/

	public PedigreeType getPedigreeType() {
		return pedigreeType;
	}

	public void setPedigreeType(PedigreeType pedigreeType) {
		this.pedigreeType = pedigreeType;
	}

	

	public Users getUsersByUsersUserId() {
		return usersByUsersUserId;
	}

	public void setUsersByUsersUserId(Users usersByUsersUserId) {
		this.usersByUsersUserId = usersByUsersUserId;
	}

	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getCalved() {
		return this.calved;
	}

	public void setCalved(String calved) {
		this.calved = calved;
	}

	public String getBbfaNo() {
		return this.bbfaNo;
	}

	public void setBbfaNo(String bbfaNo) {
		this.bbfaNo = bbfaNo;
	}

	public String getBbfaF() {
		return this.bbfaF;
	}

	public void setBbfaF(String bbfaF) {
		this.bbfaF = bbfaF;
	}

	public String getPrivateNo() {
		return this.privateNo;
	}

	public void setPrivateNo(String privateNo) {
		this.privateNo = privateNo;
	}

	public String getBand() {
		return this.band;
	}

	public void setBand(String band) {
		this.band = band;
	}

	public String getBreeder() {
		return this.breeder;
	}

	public void setBreeder(String breeder) {
		this.breeder = breeder;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getDateDelivery() {
		return this.dateDelivery;
	}

	public void setDateDelivery(String dateDelivery) {
		this.dateDelivery = dateDelivery;
	}

	public String getBreed() {
		return this.breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	public String getFarmName() {
		return this.farmName;
	}

	public void setFarmName(String farmName) {
		this.farmName = farmName;
	}

	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public String getPay() {
		return this.pay;
	}

	public void setPay(String pay) {
		this.pay = pay;
	}


	public List<Report> getReport() {
		return report;
	}

	public void setReport(List<Report> report) {
		this.report = report;
	}

}
