package com.spring.model;

// Generated Mar 29, 2015 5:24:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PedigreeType generated by hbm2java
 */
@Entity
@Table(name="pedigree_type")
public class PedigreeType implements java.io.Serializable {

	@Id
	@Column(name="type_id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	
	@Column(name="gene")
	private String gene;
	
	@Column(name="def")
	private String def;
	
	@Column(name="type")
	private String type;
	
	@Column(name="price")
	private Integer price;
	
	@Transient
	private List<Pedigree> pedigree;
	/*private Set pedigrees = new HashSet(0);*/

	public PedigreeType() {
	}

	public PedigreeType(int id) {
		this.id = id;
	}

	public PedigreeType(int id, String type, Integer price/*, Set pedigree*/) {
		this.id = id;
		this.type = type;
		this.price = price;
		/*this.pedigree = pedigree;*/
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}
	
	
	public String getDef() {
		return this.def;
	}

	public void setDef(String def) {
		this.def = def;
	}
	

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public List<Pedigree> getPedigree() {
		return pedigree;
	}

	public void setPedigree(List<Pedigree> pedigree) {
		this.pedigree = pedigree;
	}

}
