package com.spring.model;

import java.util.Date;

// Generated Mar 25, 2015 4:10:44 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TypeBill generated by hbm2java
 */
public class SearchDate implements java.io.Serializable {

	private Date date1;
	private Date date2;

	public SearchDate() {
	}

	public Date getDate1() {
		return date1;
	}

	public void setDate1(Date date1) {
		this.date1 = date1;
	}

	public Date getDate2() {
		return date2;
	}

	public void setDate2(Date date2) {
		this.date2 = date2;
	}

	



}
